version: 2.1
orbs:
  codecov: codecov/codecov@1.0.1
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - codecov/upload:
          file: coverage/coverage-final.json